server:
  port: 8087
  servlet:
    context-path: /smile-admin
    session:
      timeout: 30m

spring:
  application:
    name: smile-admin
  mvc:
    # 资源映射路径为/static/**，你想在url访问的请求路径
    static-path-pattern: /static/**
  # 资源映射地址，图片存放的真实路径
  resources:
    static-locations: file:D://cache/smile/
  # MySQL 配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.102.126.36:3306/smile_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: lt2015196
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ali-oss:
  #  查看你的bucketname的endpoint地址，如：http://oss-cn-shenzhen.aliyuncs.com
  endpoint: http://oss-cn-shanghai.aliyuncs.com
  #  你的bucketName
  bucketName: flighty-thought-oss-demo
  #  你的accessKeyId
  accessKeyId: LTAICSkNdBY7Z0KK
  #  你的accessKeySecret
  accessKeySecret: eGil6NyacGbvTWsQoMD7rs1Ocrg3iy