server:
  port: 8087
  servlet:
    context-path: /smile-admin
    session:
      timeout: 10000000m

spring:
  application:
    name: smile-admin
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  mvc:
    # 资源映射路径为/static/**，你想在url访问的请求路径
    static-path-pattern: /static/**
  # 资源映射地址，图片存放的真实路径
  resources:
    static-locations: file:D://cache/smile/
  # MySQL 配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-uf6bj20553igh785aco.mysql.rds.aliyuncs.com:3306/xm_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: xm_demo
    password: xmJK1004
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

ali-oss:
  #  查看你的bucketname的endpoint地址，如：http://oss-cn-shenzhen.aliyuncs.com
  endpoint: http://oss-cn-shanghai.aliyuncs.com
  #  你的bucketName
  bucketName: xm-prod
  #  你的accessKeyId
  accessKeyId: LTAINBhEkImrr67k
  #  你的accessKeySecret
  accessKeySecret: Y6HmSO33Jm4COWBMBuN7e7SbV7dFRu
