server:
  port: 8086
  servlet:
    context-path: /smile-appserver

spring:
  application:
    name: smile-appserver
  # MySQL 配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.102.126.36:3306/smile_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: lt5227
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
#    Redis数据库索引（默认为0）
    database: 0
#    Redis测试服务器
    host: localhost
#    Redis服务器连接端口
    port: 6379
#    Redis服务器连接密码
    password:


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
