server:
  port: 8086
  servlet:
    context-path: /smile-appserver

spring:
  application:
    name: smile-appserver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  mvc:
    # 资源映射路径为/static/**，你想在url访问的请求路径
    static-path-pattern: /static/**
  # 资源映射地址，图片存放的真实路径
  resources:
    static-locations: file:G://cache/smile/
  # MySQL 配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.102.126.36:3306/smile?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: lt2015196
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
#    Redis数据库索引（默认为0）
    database: 0
#    Redis测试服务器
    host: localhost
#    Redis服务器连接端口
    port: 6379
#    Redis服务器连接密码
    password: lt5227


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#自定义参数
app-config:
  tokenKey: 190312Smile_dev
  codeKey: 190312Smile_dev
  # Token失效时间90天
  tokenExpirationTime: 90

ali-oss:
  #  查看你的bucketname的endpoint地址，如：http://oss-cn-shenzhen.aliyuncs.com
  endpoint: http://oss-cn-shanghai.aliyuncs.com
  #  你的bucketName
  bucketName: flighty-thought-oss-demo
  #  你的accessKeyId
  accessKeyId: LTAICSkNdBY7Z0KK
  #  你的accessKeySecret
  accessKeySecret: eGil6NyacGbvTWsQoMD7rs1Ocrg3iy
